name: Run python script

on:
  push

env:
  JmeterAPIscript1: DeterAPI/sampleAPI1.jmx
  JmeterAPIscript2: DeterAPI/sampleAPI2.jmx
  JmeterUIscript1: DeterUI/sampleUI1.jmx
  JmeterUIscript2: DeterUI/sampleUI2.jmx
  
# A workflow run is made up of one or more jobs that can run sequentially
jobs:
  jmeter_API_job:
# This job will run on AWS ECS API Runner in sequence 
    runs-on: performanceAPI
    
# Git Checks-out our repository      
    name: JMeter Test Execution
    steps:    
    - name: scripts to be executed
      run: |
        echo "$JmeterAPIscript1"
        echo "$JmeterAPIscript2"
        
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install requests boto3 pandas openpyxl

   # Run the Jmeter test cases
    - name: Running JMeter for $JmeterAPIscript1
      run: |
       ls
       jmeter -n -t $JmeterAPIscript1 -Jpath=api/users?page=1 -Jduration=110 -Jusers=10 -Jrampup=10 -l ./SampleAPIjtl1.jtl
       
    - name: Running JMeter HTML for $JmeterAPIscript1
      run: |
       ls
       jmeter -Jjmeter.reportgenerator.exporter.html.series_filter="((T[0-9] {1,3}_))" -g ./SampleAPIjtl1.jtl -o ./HTMLReport1

    - name: Running JMeter for $JmeterAPIscript2
      run: |
       ls
       jmeter -n -t $JmeterAPIscript2 -Jpath=api/users?page=1 -Jduration=110 -Jusers=10 -Jrampup=10 -l ./SampleAPIjtl2.jtl

    - name: Running JMeter HTML for $JmeterAPIscript2
      run: |
       ls
       jmeter -Jjmeter.reportgenerator.exporter.html.series_filter="((T[0-9] {1,3}_))" -g ./SampleAPIjtl2.jtl -o ./HTMLReport2

   # Upload the Jmeter results    
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-API-results
        path: |
          SampleAPIjtl1.jtl
          SampleAPIjtl2.jtl
        if-no-files-found: error 
        
#filtered 
  # upload the HTML Reports    
    - name: Upload HTML Reports
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-html-API-reports
        path: |
          HTMLReport1
          HTMLReport2
        if-no-files-found: error

    # - name: Github token
    #   run: echo "MY_GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}" >> $GITHUB_ENV
      
  # Run python script to convert .json to .csv
    # - name: Run python script
    #   run: |
    #    python3 python.py

    # Run python script to compare results
    # - name: Run python script
    #   run: |
    #    python3 comparision-updated.py

  jmeter_UI_job:
# The type of runner that the job will run on
    needs: jmeter_API_job
    runs-on: performanceAPI
    
# Git Checks-out our repository      
    steps:
    - name: scripts to be executed
      run: |
        echo "$JmeterUIscript1"
        echo "$JmeterUIscript2"
        
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install requests boto3 pandas openpyxl

   # Run the Jmeter test cases
    - name: Running JMeter for $JmeterUIscript1
      run: |
       ls
       jmeter -n -t $JmeterUIscript1 -Jpath=api/users?page=1 -Jduration=110 -Jusers=10 -Jrampup=10 -l ./SampleUIjtl1.jtl
       #jmeter -n -t ${jmx-directory/scriptname} -Host ${Host} -USERID ${USERID} -Password ${Password} -Protocol ${Protocol} -threads ${threads} -rampup ${rampup} -Duration ${Duration} -Port ${Port} -testid ${testid} -CMIP ${CMIP} -DETA_OR_IDT_CLOUD ${DETA_OR_IDT_CLOUD}

    - name: Running JMeter HTML for $JmeterUIscript1
      run: |
       ls
       jmeter -Jjmeter.reportgenerator.exporter.html.series_filter="((T[0-9] {1,3}_))" -g ./SampleUIjtl1.jtl -o ./HTMLReport1

    - name: Running JMeter for $JmeterUIscript2
      run: |
       ls
       jmeter -n -t $JmeterUIscript2 -Jpath=api/users?page=1 -Jduration=110 -Jusers=10 -Jrampup=10 -l ./SampleUIjtl2.jtl

    - name: Running JMeter for $JmeterUIscript2
      run: |
       ls
       jmeter -Jjmeter.reportgenerator.exporter.html.series_filter="((T[0-9] {1,3}_))" -g ./SampleUIjtl2.jtl -o ./HTMLReport2

   # Upload the Jmeter results    
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-UI-results
        path: |
          SampleUIjtl1.jtl
          SampleUIjtl2.jtl
        if-no-files-found: error 
        
#filtered 
  # upload the HTML Reports    
    - name: Upload HTML Reports
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-html-UI-reports
        path: |
          HTMLReport1
          HTMLReport2
        if-no-files-found: error
